# Generated by Django 4.1.3 on 2022-11-18 08:51

from django.db import migrations, models
import em_asd.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', validators=[em_asd.accounts.validators.validate_file_less_than_1mb]),
        ),
    ]
