# Generated by Django 4.1.3 on 2022-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('type', models.CharField(choices=[('Positive-displacement', 'Positive-displacement'), ('Centrifugal', 'Centrifugal'), ('Dosing', 'Dosing'), ('Axial-flow', 'Axial-flow'), ('Other', 'Other')], max_length=30, verbose_name='Type')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('fluid', models.CharField(max_length=30, verbose_name='Fluid')),
                ('flow_rate', models.PositiveIntegerField(verbose_name='Flow Rate (m3/h)')),
                ('head', models.PositiveIntegerField(verbose_name='Head (m)')),
                ('power', models.PositiveIntegerField(verbose_name='Power (kW)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
