# Generated by Django 4.1.3 on 2022-11-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0002_alter_pump_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='flow_rate',
            field=models.FloatField(verbose_name='Flow Rate (m3/h)'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='head',
            field=models.FloatField(verbose_name='Head (m)'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='power',
            field=models.FloatField(verbose_name='Power (kW)'),
        ),
    ]
