# Generated by Django 4.1.3 on 2022-11-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0003_alter_pump_flow_rate_alter_pump_head_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ('tag',)},
        ),
    ]
