# Generated by Django 4.1.3 on 2022-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=30, verbose_name='Status'),
        ),
    ]
