# Generated by Django 4.1.3 on 2022-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0008_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
