# Generated by Django 4.1.3 on 2022-11-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0009_alter_activity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('ref_doc_code', models.CharField(max_length=30, verbose_name='Ref Document Code')),
                ('location', models.CharField(choices=[('Shelf 01-01', 'Shelf 01-01'), ('Shelf 01-02', 'Shelf 01-02'), ('Shelf 01-03', 'Shelf 01-03'), ('Shelf 02-01', 'Shelf 02-01'), ('Shelf 02-02', 'Shelf 02-02'), ('Shelf 02-03', 'Shelf 02-03')], max_length=30, verbose_name='Location')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pumps.pump')),
            ],
            options={
                'ordering': ('ref_doc_code',),
            },
        ),
    ]
