# Generated by Django 4.1.3 on 2022-11-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0010_spare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spare',
            new_name='Spares',
        ),
    ]
