# Generated by Django 4.1.3 on 2022-11-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0011_rename_spare_spares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
