# Generated by Django 4.1.3 on 2022-11-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0012_delete_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
