# Generated by Django 4.1.3 on 2022-11-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0013_delete_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manual',
        ),
    ]
