# Generated by Django 4.1.3 on 2022-11-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0014_delete_manual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spares',
        ),
    ]
