# Generated by Django 4.1.3 on 2022-11-22 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0015_delete_spares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='flow_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Flow Rate (m3/h)'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='head',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Head (m)'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='power',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Power (kW)'),
        ),
    ]
