# Generated by Django 4.1.3 on 2022-11-22 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pumps', '0016_alter_pump_flow_rate_alter_pump_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
