# Generated by Django 4.1.3 on 2022-11-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pumps', '0013_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=30, verbose_name='Status')),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pumps.pump')),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
    ]
