# Generated by Django 4.1.3 on 2022-12-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('due_date',), 'verbose_name_plural': 'Activities'},
        ),
    ]
