# Generated by Django 4.1.3 on 2022-11-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pumps', '0012_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('issue_date', models.DateField(verbose_name='Issuance Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('certificate_url', models.URLField(verbose_name='Certificate URL')),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pumps.pump')),
            ],
            options={
                'ordering': ('expiry_date',),
            },
        ),
    ]
